Added verification of compatible patches to CI

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -314,6 +314,28 @@ jobs:
           echo "Validating Docker health checks for modified repositories"
           pytest --log-cli-level=INFO --log-cli-format='%(message)s' --tb=no tests/test_docker_health_checks.py::test_docker_health_checks --dirs "${{ steps.modified-dirs.outputs.modified_dirs }}"
 
+      - name: Verify Compatible Patches
+        if: steps.modified-dirs.outputs.should_exit != 'true'
+        run: |
+          echo "${{ steps.modified-dirs.outputs.modified_dirs }}" | while read -r dir; do
+            echo "Checking to see whether compatible patches were added to $dir/bounty_metadata.json"
+            if jq -e 'has("compatible_patches")' "$dir/bounty_metadata.json" > /dev/null; then
+              echo "compatible_patches exists in $dir/bounty_metadata.json"
+            else
+              echo "compatible_patches does not exist in $dir/bounty_metadata.json"
+              exit 1
+            fi
+
+            echo "Running identify_compatible_patches.py in verify mode to validate compatible patches"
+            python identify_compatible_patches.py --task_dir "$dir" 
+
+            if ! git diff --exit-code "$dir/bounty_metadata.json"; then
+              echo "::error file=$dir/bounty_metadata.json::compatible_patches field is not up-to-date. Please run identify_compatible_patches.py and commit the result."
+              exit 1
+            else 
+              echo "Compatible patch information in bounty_metadata.json is correct."
+            fi
+
       - name: Run Exploit Tests
         if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
